### ISSUE TITLE
Do you have any doc about groups?

### ISSUE THREAD

**Issue by gauthierbuttez** [skoudoro/mailerlite-api-python#11]
Hi,

first of all, thank you for your work. It should be useful for my startup. 
Do you have any documentation about the group feature? Or maybe you still didn't develop anything regarding the groups?

Let me explain you my needs, you may redirect me to the good solution.

I am developing a saas business. 

1. When users didn't use at all my software, I would like to send them a series of mails. So I should create an automation series of mail for a specific group. Let's call this group "NON INSTALL GROUP". 
And then, when my software will detect a user didn't use it at all, it will add this user in this specific group : "NON INSTALL GROUP"
If the user used my software, it will check if user is in this group and remove him/her.

2. When users didn't use since a long time my software, I would like to send them a series of mails. So I should create an automation series of mail for a specific group. Let's call this group "NOT USED SINCE LONG TIME GROUP". 
And then, when my software will detect a user didn't use since a long time, it will add this user in this specific group : "NOT USED SINCE LONG TIME GROUP"
If the user used my software, it will check if user is in this group and remove him/her.

I think you get the idea of my specific needs. It is important for the retention of my saas. And RETENTION is king in SAAS business. It is very important.

Maybe there is another way to do what I need?

Kind regards

**Comment by skoudoro** [comment]
Hi @gauthierbuttez,

Thank you for asking. Most of the groups features are implemented and just need documentation.

Unfortunately, I have some deadline so I cannot work on it now until August 1rst. However, you can look at some example from @naishy [here](https://github.com/Naishy/mailerlite-api-python/commit/0e8706040c1878239ef537e38743784156e573c8#diff-04c6e90faac2675aa89e2176d2eec7d8R149). He shows how to use group with this python wrapper.

Your approach make sense to me and I hope those examples will help you.
Let me know not you have any other questions.

**Comment by Naishy** [comment]
Hi @skoudoro,
Was going to submit a PR for the doc improvements - just wanted to add a few words around the examples. I also found that adding multiple subscribers to a group (groups.add_subscribers) didn't process the response correctly, as it returns multiple subscriber details. I'll create a PR with some tests as I don't think there's coverage in that area ATM.

Thanks for the useful library - very easy to use! 👍

Tim

**Comment by skoudoro** [comment]
Great! Good catch and thank you for doing this!

I'm looking forward for your PR.

Thanks!

**Comment by skoudoro** [comment]
The doc has been updated by #12 so I am closing this issue. 

Feel free to reopen it if you have any related questions @gauthierbuttez.
