### ISSUE TITLE
Adding to a group throws an exception

### ISSUE THREAD

**Issue by poitch** [skoudoro/mailerlite-api-python#18]
When trying to add a subscriber to a group, if you don't use as_json=True then it throws an exception because it tries and convert the full response to a Subscriber when the response returned by MailerLite is different dict (imported, updated, unchanged, errors

Here is the code that fails:
```
data = {
            'email': request.user.email,
}
result = api.groups.add_subscribers(group_id, [data])
```

And the exception I get
```
  File ".../.venv/lib/python3.8/site-packages/mailerlite/group.py", line 206, in add_subscribers
    return Subscriber(**res_json)
```

**Comment by skoudoro** [comment]
Hi @poitch,

Thank you for the feedback. 

Is it with the release version or the development version? Can you tell me your version?

`python -c "import mailerlite; print(mailerlite.__version__)"`

**Comment by skoudoro** [comment]
Ok, I see, I can reproduce it with the last release (0.3.0) but the bug is fixed in the repo. 

I just created a new release  (0.4.0) and it should be ok now. 

To upgrade it @poitch :  `pip install -U mailerlite-api-python`.

I'm closing this issue. Feel free to reopen it if the bug is still here.

**Comment by poitch** [comment]
Verified. It works now, thank you.
