### ISSUE TITLE
Undefined "MailerLiteApi"

### ISSUE THREAD

**Issue by abdumuslim** [skoudoro/mailerlite-api-python#21]
Hello team,

I just install mailerlite-api with pip3 on python version 3.8.6. But I got undefined "MailerLiteApi" as the screenshot.

thanks.
![Screenshot (289)](https://user-images.githubusercontent.com/29736771/106375726-aee31680-639f-11eb-8080-81e2efce0771.png)

**Comment by skoudoro** [comment]
Hi @abdumuslim,

It looks like an environment problem. Can you just rename your file? do not call it `mailerlite.py`. it seems that python gets confused by your filename and our package name.

**Comment by abdumuslim** [comment]
woow, it's worked, ty.

**Comment by skoudoro** [comment]
Great! So I'm closing this issue and feel free to add a ⭐ on the project 😅
