### ISSUE TITLE
<lambda>() got an unexpected keyword argument 'user_agent'

### ISSUE THREAD

**Issue by vitormorales** [skoudoro/mailerlite-api-python#37]
I think mailerlite has updated some stuff on their endpoints.
The function add_single_subscriber on group module is failing because this new parameter(s). For instance "user_agent".

Specifically here: 
https://github.com/skoudoro/mailerlite-api-python/blob/e1aa102218a5991cf169b372d8eff6d98ac44639/mailerlite/group.py#L248

This may affect other parts. I didn't test it.
I can take a look later on this week but feel free to fix this. I'll need this soon.

Cheers!

**Comment by skoudoro** [comment]
Hi @vitormorales, 

Thank you for the feedback. 

This PR https://github.com/skoudoro/mailerlite-api-python/pull/36 should fix it. 

I will try to release the package this week. 

Thanks !
