### ISSUE TITLE
AttributeError: 'MailerLiteApi' object has no attribute 'campaign'

### ISSUE THREAD

**Issue by skaplichniy** [skoudoro/mailerlite-api-python#45]
When I try to send a campaign using an example in README file I got an error _AttributeError: 'MailerLiteApi' object has no attribute 'campaign'_. I think it suppose to be api.campaign**s**.create, api.campaign**s**.update, api.campaign**s**.send

**Comment by skoudoro** [comment]
Hi @skaplichniy,

Thanks for the feedback and good catch! I will update the README later in the day.

**Comment by skoudoro** [comment]
Fixed!  Thanks again
