### ISSUE TITLE
Endless 'sending' status

### ISSUE THREAD

**Issue by skaplichniy** [skoudoro/mailerlite-api-python#46]
I try to use the script from README, it seems that Mailerlite receives it and starts to build a campaign, but nothing happens. There is a 'sending' status in the admin panel, but still no mail on the inbox. Am I missing something?

```python
from mailerlite import MailerLiteApi
api = MailerLiteApi('mailerlite-api-key')

data = {"subject": "Regular campaign subject",
        "name": "Regular campaign name",
        "groups": [GroupID],
        "type": "regular"}

_, res = api.campaigns.create(data)
campaign_id = res['id']

html = '<head></head><body><h1>Your Title</h1><p>Your Content</p><p><small>'
html += '<a href=\"{$unsubscribe}\">Unsubscribe</a></small></p></body>'
plain = "Your email client does not support HTML emails. "
plain += "Open newsletter here: {$url}. If you do not want"
plain += " to receive emails from us, click here: {$unsubscribe}"

api.campaigns.update(campaign_id, html=html, plain=plain)
api.campaigns.send(campaign_id)
```
![2022-01-31_14-57-40](https://user-images.githubusercontent.com/86144865/151872060-4723b2f1-ccf1-4c6e-a12f-e2dc0f17393d.png)

**Comment by skoudoro** [comment]
Not sure what is happening but I would recommend checking your campaign type.

if you look at the documentation [here](https://developers.mailerlite.com/reference/campaign-actions-and-triggers) campaigns should be in draft and has step value equal to 3. 

The current code does not check these 2 conditions yet.  Can you check this? 

also, can you show the return value of `api.campaigns.send(campaign_id)`?

Thanks

**Comment by skaplichniy** [comment]
It's still a little bit confusing for me how to check these conditions.

>also, can you show the return value of api.campaigns.send(campaign_id)?

```python
{
  "error": {
    "code": 404,
    "message": "Campaign not found"
  }
}
```

Thank you for your help!

**Comment by skaplichniy** [comment]
@skoudoro 

> also, can you show the return value of api.campaigns.send(campaign_id)?

Here it is:

`(200, {'id': 47726474, 'total_recipients': 0, 'type': 'regular', 'extra_type': None, 'name': 'Regular newsletter', 'status': 'outbox', 'step': 3, 'send_rule': None, 'opened': {'count': None, 'rate': None}, 'clicked': {'count': None, 'rate': None}, 'followup_info': {'send_type': 'regular', 'followup_send_type': None}, 'ab_info': {'send_type': 'regular', 'ab_win_type': None}, 'date_created': '2022-02-03 19:43:24', 'date_send': '2022-02-03 19:43:00', 'date_end': None, 'mail': {'id': 50523986, 'date': '2022-02-03 19:43:24', 'subject': "subject", 'code': 'i2u6p4b6a1', 'from': 'mymail@gmail.com', 'from_name': 'Myname', 'url': 'url-letter', 'send_date': '2022-02-03 19:43:00', 'host': 'mailerlite.com', 'type': 'template', 'screenshot': 'https://static.mailerlite.com/images/newsletter_screenshot2.png', 'screenshot_big': 'https://static.mailerlite.com/images/newsletter_screenshot2.png', 'updated': '2022-02-04 01:43:24', 'track_opens': 1, 'language': {'code': 'en', 'title': 'English'}, 'groups': [{'id': 111111111, 'name': 'subs', 'total': 0, 'active': 0, 'unsubscribed': 0, 'bounced': 0, 'unconfirmed': 0, 'junk': 0, 'sent': 0, 'opened': 0, 'clicked': 0, 'ordering': 0, 'updating': 0, 'user_id': 0, 'date': '2022-01-31 10:13:25', 'updated': '2022-01-31 10:13:55'}]}, 'mails': [{'id': 111111111, 'date': '2022-02-03 19:43:24', 'subject': "Subject", 'code': 'code', 'from': 'mymail@gmail.com', 'from_name': 'myname', 'url': 'url', 'send_date': '2022-02-03 19:43:00', 'host': 'mailerlite.com', 'type': 'template', 'screenshot': 'https://static.mailerlite.com/images/newsletter_screenshot2.png', 'screenshot_big': 'https://static.mailerlite.com/images/newsletter_screenshot2.png', 'updated': '2022-02-04 01:43:24', 'track_opens': 1}], 'includes_survey': False, 'has_ecommerce': False, 'report_date': None})`

**Comment by skaplichniy** [comment]
Ooops, after I filed the whole letter it started to work!

**Comment by skoudoro** [comment]
Cool 👍🏾 , thanks for the feedback. Sorry I did not get back to you, quite a busy week.

> after I filed the whole letter

What do you mean by that?

**Comment by skaplichniy** [comment]
> What do you mean by that?

As soon as I added the whole content of my letter (not just the test message) it accidentally started to work!
