### ISSUE TITLE
No module named 'mailerlite'

### ISSUE THREAD

**Issue by dmalis** [skoudoro/mailerlite-api-python#47]
Installed 0.10.0 via pip [venv], still receiving:

from mailerlite import MailerLiteApi

ModuleNotFoundError: No module named 'mailerlite'

py3.8

**Comment by skoudoro** [comment]
Hi @dmalis,

That's strange, can you provide more detailed information.  

> ModuleNotFoundError: No module named 'mailerlite'

This means that there is an installation issue. You might have conflict in your environment.  Usually, this is not related to the package itself.

Please keep me updated

**Comment by dmalis** [comment]
Hi @skoudoro and thanks for quick response.

It's a pycharm, py3.8 on windows project - with 60+ libraries already in requirements.txt. 

Including mailerlite-api-python==0.10.0 installs the library - it's in site-packages just like all other libs from requirements.txt (Flask, sendgrid,...), but is the only one that raises import error.

I've searched for possible "mailerlite.py" file within the project, but there is none. The only mailerlite string occurrence is from the installed library.

I guess this doesn't help much, I might try creating new project installing only ML and flask to see whether this works.

**Comment by dmalis** [comment]
@skoudoro interestingly it works without any modifications on my mac. I wish I knew what are the differences that prevent win11 machine from working.

**Comment by skoudoro** [comment]
I suppose this issue has been fixed so I am closing for now. Feel free to reopen it if it is not the case.
