### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'webform_subscribe_date'

### ISSUE THREAD

**Issue by jsemrau** [skoudoro/mailerlite-api-python#49]
**Description**
I am trying to extract all subscribers from my mailerlite account through

1. api.subscribers.all(stype='active')
2. api.subscribers.active()
3. api.subscribers.groups(id=group_id)

Platform Ubuntu 20.10
Python 3.8.10

**Observed behavior:**
The python script failed with webform_subscribe_date missing.
This : TypeError: __new__() got an unexpected keyword argument 'webform_subscribe_date'

**Expected behavior:**
The python layer returns all registered and active user accounts .

**Comment by skoudoro** [comment]
Hi @jsemrau,

it has been fixed by #43.  you just need to update your version:  `pip install -U mailerlite-api-python`

Closing, feel free to reopen the issue if you still have a problem.
