### ISSUE TITLE
Mailerlite does not send mail with "sending..."

### ISSUE THREAD

**Issue by tuarodevop** [skoudoro/mailerlite-api-python#52]
Code for creating campaigns and sending mail by running campaigns.

```python
from mailerlite import MailerLiteApi
from pprint import pprint
import time

api = MailerLiteApi('******************')

data = {"subject": "Regular campaign subject",
            "name": "Regular campaign name",
            "groups": [111509512],
            "type": "regular"}
_, res = api.campaigns.create(data)
campaign_id = res['id']

html = '<head></head><body><h1>Your Title</h1><p>Your Content</p><p><small>'
html += '<a href=\"{$unsubscribe}\">Unsubscribe</a></small></p></body>'
plain = "Your email client does not support HTML emails. "
plain += "Open newsletter here: {$url}. If you do not want"
plain += " to receive emails from us, click here: {$unsubscribe}"

api.campaigns.update(campaign_id, html=html, plain=plain)
api.campaigns.send(campaign_id)
```

---------------------------------------

Running this code creates a campaign and moves the campaign to the mailerlite outbox. After 1 minute, it says it has been sent and goes to Sent. However, the mail is not actually sent, and when I click on the campaign in Sent, it says Sending...

Am I the only one like this? I would appreciate it if you could tell me the solution.

This is a screenshot.
![화면 캡처 2022-09-02 110920](https://user-images.githubusercontent.com/112833933/188340595-b7425135-9e80-41a5-b378-ffa8ed3db84b.png)

**Comment by tuarodevop** [comment]
The Modify part seems to be a problem.
I modified it to the official API and sent it, so it works normally.

**Comment by skoudoro** [comment]
Hi @tuarodevop,

sorry for the late reaction, I just see this issue.

> The Modify part seems to be a problem.

Thank you for the feedback. Can you be more explicit? What did you exactly modify?

**Comment by tuarodevop** [comment]
I just modified the api.campaigns.update part.

```python
data = {"subject": "Regular campaign subject1",
            "name": "Regular campaign name11",
            "groups": [111509512],
            "type": "regular"}
_, res = api.campaigns.create(data)
campaign_id = res['id']
print(campaign_id)

# 캠페인 내용 수정
url = f"https://api.mailerlite.com/api/v2/campaigns/{campaign_id}/content"

payload = {
    "html": "<html><head><title>Email template</title></head><body><h1>1Title</h1><p>Content</p><p><small><a href=\"{$unsubscribe}\">Unsubscribe</a></small></p></body></html>",
    "plain": "Your email client does not support HTML emails. Open newsletter here: {$url}. If you do not want to receive emails from us, click here: {$unsubscribe}",
    "auto_inline": True
}
headers = {
    "Accept": "application/json",
    "X-MailerLite-ApiDocs": "true",
    "Content-Type": "application/json",
    "X-MailerLite-ApiKey": "************************"
}

response = requests.put(url, json=payload, headers=headers)

# print(response.text)

api.campaigns.send(campaign_id)
```


When I edit and run it like this, it sends mail properly.

**Comment by skoudoro** [comment]
ok, strange, apart from the `auto_inline` option, the code is exactly the same. 

I will have to introspect.  No time this week, maybe this weekend.

Thank you very much for the feedback!

**Comment by tuarodevop** [comment]
thank you!
Am I not the only one having this problem?

I hope it is easy to find the reason and fix it.
