### ISSUE TITLE
Base URL for API endpoints has changed?

### ISSUE THREAD

**Issue by telefunkst** [skoudoro/mailerlite-api-python#53]
It seems like the URL set in MAILERLITE_API_V2_URL is no longer correct: https://api.mailerlite.com/api/v2/
Mailerlite API documentation suggests using https://connect.mailerlite.com

I am having issues with creating a campaign, and I believe this is the cause. Perhaps MAILERLITE_API_V2_URL should be updated?

**Comment by skoudoro** [comment]
Hi @telefunkst,

Good catch! Thank you for letting me know! I will update that tomorrow and do a new release. 
It seems they made a big update on the developer website. I need to update other link also.

Thanks !

Ps: feel free to contribute and make a PR if you have time to do it today

**Comment by skoudoro** [comment]
Hi @telefunkst,

After doing some tests, I realized that the current url is working correctly. 

it seems they renamed the API and this one is not anymore the V2 but the V1 / V2_BETA. 

So I will just rename it and try to add the new V2 API on this project.

Thanks again, closing for now

**Comment by skoudoro** [comment]
ok, it seems they broke the old version and the new one is not ready and use sometimes the old version. it is messy.

We are not the only one encountering this problem as you can see on this issue: https://github.com/jpalumickas/mailerlite-ruby/issues/38
