### ISSUE TITLE
Ability to fetch a subscribers status in a group?

### ISSUE THREAD

**Issue by GusBricker** [skoudoro/mailerlite-api-python#56]
Hi,

Love this package, its very useful so thanks for your hard work.

I was looking thru the API this package provides, but cannot see a way to fetch a subscribers status in a group (eg: active, unsubscribed, unconfirmed, bounced, junk). Just wondering if you know of how to do this, looking at both V1 & V2 API docs, its very unclear if this is even possible from mailerlite's API.

Cheers

**Comment by skoudoro** [comment]
Hi @GusBricker,

Thank you for the feedback, feel free to star the project, it helps to show love 😅 .

Not sure, but what I will do is something like that (Not tested):

```python

all_active_in_group = api.groups.subscribers(group_id=12345, stype='active')
all_unsbscribed_in_group = api.groups.subscribers(group_id=12345, stype='unsubscribed')

etc....
```

Let me know if it works correctly

**Comment by GusBricker** [comment]
Hi @skoudoro 

I am only after an individuals status in a group, did not want to have to iterate through all active subscribers as it could potentially take a long time.

Thanks

**Comment by skoudoro** [comment]
So it means you know the subscriber `ID`

```python
# Get one subscriber from a Group
sub = api.groups.subscriber(group_id=12345, subscriber_id=54321)
# Get his status (eg: active, unsubscribed, unconfirmed, bounced, junk)
print(sub.type)
```

hope it helps

**Comment by skoudoro** [comment]
ok, closing the issue.

feel free to reopen it if you still have a problem.
