### ISSUE TITLE
MailerLite doesn't allow to update the email

### ISSUE THREAD

**Issue by kaiofreitas** [skoudoro/mailerlite-api-python#8]
Hi, I've tried your example on how to update a subscriber profile, but I realized it's not possible to use the email field.

Reading MailerLite's documentation, they suggest creating a new subscriber when the email changes.

Is that right?

`data = {'name': 'John',
            'email': 'demo-678@mailerlite.com',
            'fields': {'company': 'MailerLite'}
            }
api.subscribers.update(data, id='1343965485')`

**Comment by skoudoro** [comment]
Hi @kaiofreitas,

Good catch! The `email` can not be updated and we should create a new subscriber, that's right. I will correct the documentation and add a check in the function.

Thank you for your feedback!

**Comment by skoudoro** [comment]
I just fixed it, Thank you again

**Comment by kaiofreitas** [comment]
Just one more question: is it possible to get this update via pip?

**Comment by skoudoro** [comment]
The plan was to do a release on Saturday. 

But ok, I will try to do it before Wednesday

**Comment by skoudoro** [comment]
Finally, I just updated @kaiofreitas. No reason to wait and I had 15min free.

**Comment by skoudoro** [comment]
just run `pip install -U mailerlite-api-python` or `pip install mailerlite-api-python==0.2.0`
